Some cosmetic changes in this doc and the tests (test-suite dir renamed as tests), but no changes to tewiba itself, so no version number increase.

diff --git a/tests/tewiba b/tests/tewiba
--- a/tests/tewiba
+++ b/tests/tewiba
@@ -1,5 +1,5 @@
 #!/bin/bash
-export TEWIBA=1.1
+export TEWIBA=1.3.1
 USAGE='tewiba [options] [tests...]
 Tewiba: TEst WIth BAsh: a simple test suite, in the spirit of shell scripting
 Runs the test suite, on all tests in the current dir (default), 
@@ -37,8 +37,9 @@ How to write tests:
      TEST message  prints (sub)test name if verbose
      TERR message  declares an error, but continues the tests
      FERR message  fatal error: also aborts the current test file
-     TEND          terminates your test script (alias for: exit $TFAILS)
-                   the only function really mandatory.
+     TEND          MANDATORY: terminates your test script.
+                   (an alias for: exit $TFAILS)
+                   This is the only function really mandatory in a test file.
      TINIT id...   For each id (composed of letters, numbers, and _ - .)
                    ensures that files __INIT__id and __END__id are sourced,
                    if they exist, before and after all tests of the dir,
@@ -51,6 +52,11 @@ How to write tests:
                    [ -n "$TEWIBA" ] || exec tewiba -v "$0"
                    so that the test file can be executed standalone
      $TEWIBADIR    the original directory where tewiba was run
+   * IMPORTANT: the shell function TCLEANUP must be called at the end of the
+     tests, to clean the temporary data. tewiba traps the signal 0 for this.
+     if you redefine trap 0 in your tests, or in a script you source, you 
+     should either make your trap function also call TCLEANUP, or redo a
+     "trap TCLEANUP 0" at the end of your tests.
 
 Options:
    -v      verbose: prints each test name as it is run, as well as its stdout
@@ -62,6 +68,8 @@ Options:
            thus ranges are possible: -l 0-3 matches a TLEVEL 17a
    -s      standalone: do not read __INIT__ nor __END__ files
    -e file outputs the total number of errors in the file. 
+   -f      forces running tests files even without a TEND directive in them.
+           Or add this line in the test file: #TNOEND
 
 Exemple simple test file:
   #!/bin/bash
@@ -83,45 +91,52 @@ export ts_standalone=false
 export TEWIBADIR="$PWD"
 export TLEVELS=
 export TV=
+export must_tend=true
 
-err () { echo "***ERROR: $*" >&2; exit 1; }
-warn () { echo "###Warning: $*" >&2; }
-V () { :;}; T () { :;}; TV=false; E () { echo "$@";}; En () { echo -n "$@";}
-Vn () { :;}
-while test "_${1#-}" != "_$1" -a "_${1//-/}" != "_";do case "$1" in
-  -v) V () { echo "== $*" >&2;}; Vn () { echo -n "== $*" >&2;}; TV=true
-      T () { local i;En "==";for i in $*;do En " $i="`eval E '$'$i`;done;E;};;
-  -x) debug=true; rm -f $debuglog;;
-  -e) statusfile="$2"; shift;;
-  -l) TLEVELS="$2"; shift;;
-  -s) ts_standalone=true;;
-  -V) echo "$TEWIBA"; exit 0;;
-  *) echo "$USAGE"; exit 1;
-esac;shift; done; if test "_$1" = "_--";then shift; fi
+err(){ echo "***ERROR: $*" >&2; TCLEANUP; exit 1;}
+warn(){ echo "###Warning: $*" >&2;}
+V(){ :;};T(){ :;};TV=false;E(){ echo "$@";};En(){ echo -n "$@";};Vn(){ :;}
+while getopts e:l:xsvV\?h o; do case "$o" in
+  e) statusfile="$OPTARG";;
+  l) TLEVELS="$OPTARG";;
+  x) debug=true; rm -f $debuglog;;
+  s) ts_standalone=true;;
+  f) must_tend=false;;
+  V) echo "$TEWIBA"; exit 0;;
+  v) V(){ echo "== $*" >&2;};Vn(){ echo -n "== $*" >&2;};TV=true
+     T(){ local i;En "==";for i in $*;do En " $i="`eval E '$'$i`;done;E;};;
+  h|'?') echo "$USAGE"; exit 1;;
+esac;done;shift $((OPTIND-1))
 
 ############################################ Convenience funcs & vars
 export ts_failures=0
 export tmp=/tmp/tewiba.$$
-ttmp=/tmp/tewiba-main.$$
+export ttmp=/tmp/tewiba-main.$$
 export TINITS=$ttmp.tinits.
 export nl=$'\n' #'
 export TFAILS=0
 export TDIR=
 export TIDS=' '
-TLEVEL () { [ -z "$TLEVELS" ] || [[ $* =~ [$TLEVELS] ]] || exit 0; }
-TLEVEL_ONLY () { [[ $* =~ [$TLEVELS] ]] || exit 0; }
+TLEVEL () { [ -z "$TLEVELS" ] || [[ $* =~ [$TLEVELS] ]] || ts_exit; }
+TLEVEL_ONLY () { [[ $* =~ [$TLEVELS] ]] || ts_exit; }
 TEST () { $TV && echo "== $*"; }
-TERR () { echo "***TEST ERROR ${0##*/}*** $*" >&2; let TFAILS++; }
-FERR () { echo "***FATAL ERROR ${0##*/}*** $*" >&2;let TFAILS++;exit $TFAILS; }
-TEND () { exit $TFAILS; }
+TERR () { echo "***TEST ERROR ${0##*/}*** $*" ; let TFAILS++; }
+FERR () { echo "***FATAL ERROR ${0##*/}*** $*" ; let TFAILS++; ts_exit $TFAILS; }
+TEND () { ts_exit $TFAILS; }
 TINIT () { # TINITS is a per-dir file containing the loaded IDs
   local id="${1//[^-_.a-zA-Z0-9/}"; [ -n "$id" ] || return; 
   fgrep -qxs $id $TINITS && return; echo $id >>$TINITS
   [ -x __INIT__$id ] && source __INIT__$id
 }
-TCLEANUP () { rm -rf $ttmp $ttmp.* $tmp $tmp.*; }; trap TCLEANUP 0
+TCLEANUP () { # with guards to avoid disaster if a test undefined the vars
+  [ -n "$ttmp" ] && rm -rf $ttmp $ttmp.*
+  [ -n "$tmp" ] && rm -rf $tmp $tmp.*
+}
+trap TCLEANUP 0
+# low-level exit, runs TCLEANUP for safety if our trap 0 was overriden
+ts_exit() { : TCLEANUP; exit "${1:-0}"; }
 
-export -f TLEVEL TEST TERR FERR TEND TINIT TCLEANUP
+export -f TLEVEL TEST TERR FERR TEND TINIT ts_exit TCLEANUP
 
 ############################################ Code
 
@@ -190,13 +205,18 @@ ts_level () {
 ts_test () {
   local t="$1" s="#################################"
   ts_level "$t" || return
+  ! egrep -q '^([^#]*;|[[:space:]]*)TEND([;[:space:]]|$)' "$t" && $must_tend &&
+  ! grep -q '^ *#TNOEND' "$t" && [ -s "$t" ] && \
+      err "Test file \"$t\" does not have a TEND statement. Use -f to force."
   ts_init
   TFAILS=0
   if $debug; then
     echo "$s$s$nl$s Test: $t$nl$s$s" >>$debuglog
-    bash -x "$t" 2>>$debuglog; status=$?
+    # RUN + Trace
+    bash -x "$t" >>$debuglog 2>&1; status=$?
   else
     $TV && echo -n "== Test: $t:"
+    # RUN
     ./"$t" >$ttmp.out 2> >(tee -a $ttmp.err >&1); status=$?
     let 'ts_failures += status'
     if [ $status = 0 ]; then
@@ -216,7 +236,7 @@ ts_test () {
       fi
     fi
     if $TV && test -s $ttmp.out; then print_indent $ttmp.out; fi
-    rm -rf $tmp $tmp.*
+    [ -n "$tmp" ] && rm -rf $tmp $tmp.*
   fi
 }
 
@@ -234,7 +254,8 @@ else
       if [[ $t =~ / ]]; then ts_test_path "$t"
       else ts_test "$t"
       fi
-    else err "$t is not a test!"
+    elif [ -e "$t" ]; then err "$t not found!"
+    else err "$t is not executable!"
     fi
   done
 fi
@@ -246,4 +267,4 @@ else echo "== ***** Total tests failed: $ts_failures *****"
 fi
 $debug && echo "== log of execution in $debuglog"
 [ -n "$statusfile" ] && echo "$ts_failures" >"$statusfile"
-exit $ts_failures
+ts_exit $ts_failures
